{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "edgedb.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
