apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgedb.fullname" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "edgedb.selectorLabels" . | nindent 4 }}
